[package]
name = "boids"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
rand = "0.9.2"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
